name: AuctionHouse
version: '${version}'
main: me.elaineqheart.auctionHouse.AuctionHouse
api-version: '26.2'
folia-supported: true
canvas-supported: true
authors: [ ElaineQheart ]
website: https://www.youtube.com/@elaineqheart
depend: [ Vault ]
softdepend: [ PlaceholderAPI, Locale-API ]
permissions:
  auctionhouse.ah:
    description: allows the player to use /ah
    default: true
